// <auto-generated />
using System;
using Entity_Framework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entity_Framework.Migrations
{
    [DbContext(typeof(HotelsContext))]
    [Migration("20190614161501_CreateHotelsDB")]
    partial class CreateHotelsDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity_Framework.Tables.Hotels", b =>
                {
                    b.Property<int>("hotelsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address");

                    b.Property<int>("foundationYear");

                    b.Property<bool>("isActive");

                    b.Property<string>("name");

                    b.HasKey("hotelsID");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Entity_Framework.Tables.Rezervation", b =>
                {
                    b.Property<int>("rezervationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("endRezervation");

                    b.Property<int>("roomsID");

                    b.Property<DateTime>("startRezervation");

                    b.Property<int>("usersID");

                    b.HasKey("rezervationID");

                    b.ToTable("Rezervations");
                });

            modelBuilder.Entity("Entity_Framework.Tables.Rooms", b =>
                {
                    b.Property<int>("roomsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("capability");

                    b.Property<int>("comfortLevel");

                    b.Property<int>("hotelsID");

                    b.Property<int>("number");

                    b.Property<decimal>("price");

                    b.HasKey("roomsID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Entity_Framework.Tables.Users", b =>
                {
                    b.Property<int>("usersID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.HasKey("usersID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
